<?php

/** Implements hook_form_FORM_ID_alter() **/
function community_framework_form_webform_component_edit_form_alter(&$form, &$form_state, $form_id) {
  //printr($form);
  //print $form_id;
  if ($form['type']['#value'] != 'fieldset') {
    $points = array();
    for ($i = 0; $i <= 100; $i++) {
      $points[$i] = $i;
    }
    $default_tier = community_framework_get_tier($form['nid']['#value'], $form['cid']['#value']);
    //printr($default_tier);
    $form['community_framework_tier'] = array(
      '#type' => 'select',
      '#title' => t('Tier'),
      '#description' => t('Which Community Framework tier is this question on?'),
      '#options' => array(1 => 1, 2 => 2, 3 => 3),
      '#default_value' => $default_tier,
      '#weight' => -1000,
    );
  }
  
  //$form['weight']
}

function community_framework_webform_component_insert($component) {
  community_framework_webform_component_update($component);
}
function community_framework_webform_component_update($component) {
  if (isset($component['community_framework_tier'])) {
    community_framework_save_tier($component['nid'], $component['cid'], $component['community_framework_tier']);
  }
}

function community_framework_save_tier($nid, $cid, $tier) {
  db_merge('assessment_question_tiers')
    ->key(array('nid' => $nid, 'cid' => $cid))
    ->fields(array(
      'tier' => $tier,
    ))->execute();
}

function community_framework_get_tier($nid, $cid) {
  $tier = db_query("SELECT tier FROM {assessment_question_tiers} WHERE nid = :nid AND cid = :cid",
                      array(':nid' => $nid, ':cid' => $cid))->fetchField();
                      
  return $tier ? $tier : FALSE;
}

function community_framework_theme() {
  return array(
    'community_framework_results' => array(
      'variables' => array('tier1' => NULL, 'tier2' => NULL, 'tier3' => NULL),
      'template' => 'community-framework-results',
    ),
  );
}
